name: wifisignal
description: WiFi信号测试工具
publish_to: 'none' # 将项目标记为不发布到 pub.dev
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # iOS风格的图标
  wifi_iot: ^0.3.18 # 用于操作WiFi功能
  network_info_plus: ^4.0.0 # 用于获取设备网络信息
  fl_chart: ^0.65.0 # 用于创建图表和数据可视化
  provider: ^6.0.5 # 状态管理工具
  vibration: ^1.8.3 # 控制设备振动
  get_it: ^7.6.7 # 依赖注入工具
  ping_discover_network_forked: ^0.0.1 # 网络Ping工具
  webview_flutter: ^4.4.2 # 在应用中嵌入网页

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # 提供 Flutter 开发的代码规范
  flutter_launcher_icons: ^0.13.1 # 图标生成工具

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png" # 图标文件路径

flutter:
  uses-material-design: true # 启用 Material Design
  assets:
    - assets/icons/ # 图标资源